# Generated by Django 4.2.7 on 2023-12-09 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpost",
            name="max_participants",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="eventpost",
            name="min_participants",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name="Toon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("realm", models.CharField(max_length=200)),
                ("level", models.IntegerField(default=0)),
                ("primary_role", models.CharField(default="dps", max_length=200)),
                ("secondary_role", models.CharField(max_length=200, null=True)),
                ("gear_score", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
