# Generated by Django 4.2.7 on 2023-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0005_alter_toon_primary_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toon",
            name="level",
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name="toon",
            name="primary_role",
            field=models.CharField(
                choices=[
                    ("tank", "Tank"),
                    ("heal", "Heal"),
                    ("damage", "Damage"),
                    ("hybrid", "Hybrid"),
                    ("none", "None"),
                ],
                default="damage",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="toon",
            name="realm",
            field=models.CharField(
                choices=[
                    ("americas", "Americas"),
                    ("europe", "Europe"),
                    ("korea", "Korea"),
                    ("taiwan", "Taiwan"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="toon",
            name="secondary_role",
            field=models.CharField(
                choices=[
                    ("tank", "Tank"),
                    ("heal", "Heal"),
                    ("damage", "Damage"),
                    ("hybrid", "Hybrid"),
                    ("none", "None"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
