# Generated by Django 4.2.7 on 2023-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0007_toon_realm_region_alter_toon_realm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="user",
            new_name="name",
        ),
        migrations.AddField(
            model_name="eventpost",
            name="participants",
            field=models.ManyToManyField(to="eventapp.player"),
        ),
    ]
