# Generated by Django 4.2.7 on 2023-12-13 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0003_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toon",
            old_name="player",
            new_name="player_name",
        ),
    ]
