# Generated by Django 4.2.7 on 2023-12-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0004_rename_player_toon_player_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toon",
            name="primary_role",
            field=models.CharField(default="damage", max_length=200),
        ),
    ]
