# Generated by Django 4.2.7 on 2023-12-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0006_alter_toon_level_alter_toon_primary_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toon",
            name="realm_region",
            field=models.CharField(
                choices=[
                    ("americas", "Americas"),
                    ("europe", "Europe"),
                    ("korea", "Korea"),
                    ("taiwan", "Taiwan"),
                ],
                default="americas",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="toon",
            name="realm",
            field=models.CharField(max_length=30),
        ),
    ]
