# Generated by Django 4.2.7 on 2023-12-15 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventapp", "0008_rename_user_player_name_eventpost_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventapp.eventpost",
                    ),
                ),
                (
                    "toon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventapp.toon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee",
                "verbose_name_plural": "Attendees",
                "unique_together": {("event", "user")},
            },
        ),
    ]
