# Generated by Django 4.2.7 on 2023-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0010_toon_tclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpost",
            name="participants",
            field=models.ManyToManyField(to="eventapp.toon"),
        ),
    ]
