# Generated by Django 4.2.7 on 2023-12-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0011_alter_eventpost_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpost",
            name="participants",
        ),
        migrations.AddField(
            model_name="eventpost",
            name="participants",
            field=models.CharField(default="foo", max_length=255),
        ),
    ]
